export const HURLING_TEAMS = [
  { name: 'Kilkenny', emoji: '🐝', province: 'Leinster' },
  { name: 'Limerick', emoji: '⚡', province: 'Munster' },
  { name: 'Cork', emoji: '🔴', province: 'Munster' },
  { name: 'Tipperary', emoji: '🔵', province: 'Munster' },
  { name: 'Galway', emoji: '🟤', province: 'Connacht' },
  { name: 'Waterford', emoji: '💎', province: 'Munster' },
  { name: 'Clare', emoji: '🟡', province: 'Munster' },
  { name: 'Wexford', emoji: '💛', province: 'Leinster' },
  { name: 'Dublin', emoji: '🏙️', province: 'Leinster' },
  { name: 'Offaly', emoji: '🌿', province: 'Leinster' },
  { name: 'Antrim', emoji: '🦌', province: 'Ulster' },
  { name: 'Laois', emoji: '⭕', province: 'Leinster' },
];

export const FOOTBALL_TEAMS = [
  { name: 'Kerry', emoji: '⭐', province: 'Munster' },
  { name: 'Dublin', emoji: '🏙️', province: 'Leinster' },
  { name: 'Galway', emoji: '🟤', province: 'Connacht' },
  { name: 'Mayo', emoji: '🟢', province: 'Connacht' },
  { name: 'Donegal', emoji: '🟡', province: 'Ulster' },
  { name: 'Tyrone', emoji: '🔴', province: 'Ulster' },
  { name: 'Meath', emoji: '💚', province: 'Leinster' },
  { name: 'Roscommon', emoji: '🟡', province: 'Connacht' },
  { name: 'Cork', emoji: '🔴', province: 'Munster' },
  { name: 'Monaghan', emoji: '🔵', province: 'Ulster' },
  { name: 'Kildare', emoji: '⬜', province: 'Leinster' },
  { name: 'Armagh', emoji: '🟠', province: 'Ulster' },
];

export const COUNTIES = [
  'Antrim', 'Armagh', 'Carlow', 'Cavan', 'Clare', 'Cork',
  'Derry', 'Donegal', 'Down', 'Dublin', 'Fermanagh', 'Galway',
  'Kerry', 'Kildare', 'Kilkenny', 'Laois', 'Leitrim', 'Limerick',
  'Longford', 'Louth', 'Mayo', 'Meath', 'Monaghan', 'Offaly',
  'Roscommon', 'Sligo', 'Tipperary', 'Tyrone', 'Waterford',
  'Westmeath', 'Wexford', 'Wicklow',
];

export const COMPETITIONS = [
  'Allianz Hurling League',
  'Allianz Football League',
  'Leinster Championship',
  'Munster Championship',
  'Connacht Championship',
  'Ulster Championship',
  'All-Ireland Championship',
  'All-Ireland Final',
  'Club Championship',
  'Other',
];

export const INITIAL_MATCHES = [
  {
    id: '1',
    sport: 'Hurling',
    homeTeam: 'Kilkenny',
    awayTeam: 'Tipperary',
    homeScore: { goals: 2, points: 18 },
    awayScore: { goals: 1, points: 14 },
    date: '2026-02-15',
    venue: 'Nowlan Park, Kilkenny',
    competition: 'Allianz Hurling League',
    hasProgramme: true,
    notes: 'Brilliant atmosphere in Nowlan Park. Kilkenny\'s first half dominance was something else — TJ Reid was unreal. Stayed for a pint in the city afterwards. One of the best days out this year.',
    standsidersCount: 312,
    friendsCount: 3,
  },
  {
    id: '2',
    sport: 'Football',
    homeTeam: 'Dublin',
    awayTeam: 'Kerry',
    homeScore: { goals: 2, points: 15 },
    awayScore: { goals: 1, points: 18 },
    date: '2026-02-08',
    venue: 'Croke Park, Dublin',
    competition: 'Allianz Football League',
    hasProgramme: false,
    notes: 'Incredible game. Kerry snatched it at the end. The Hill was electric.',
    standsidersCount: 1847,
    friendsCount: 7,
  },
  {
    id: '3',
    sport: 'Football',
    homeTeam: 'Galway',
    awayTeam: 'Mayo',
    homeScore: { goals: 0, points: 14 },
    awayScore: { goals: 1, points: 12 },
    date: '2026-01-25',
    venue: 'Pearse Stadium, Galway',
    competition: 'Allianz Football League',
    hasProgramme: true,
    notes: 'Great Connacht derby. Pearse Stadium was buzzing.',
    standsidersCount: 204,
    friendsCount: 1,
  },
];

export const STANDSIDERS = [
  {
    id: '1',
    name: "Séan Ó'Brien",
    handle: '@seanob',
    county: 'Kilkenny',
    games: 52,
    programmes: 34,
    avatarColor: '#C8952A',
    initials: 'S',
    following: true,
    recentActivity: "logged their 52nd game",
    recentMatch: "⚾ Kilkenny v Tipperary · 15 Feb",
    timeAgo: '2 hours ago',
  },
  {
    id: '2',
    name: 'Máire Breathnach',
    handle: '@mairebn',
    county: 'Dublin',
    games: 38,
    programmes: 28,
    avatarColor: '#1C2B6E',
    initials: 'M',
    following: true,
    recentActivity: 'added a programme to their collection',
    recentMatch: '🏈 Dublin v Kerry · 8 Feb',
    timeAgo: 'Yesterday',
  },
  {
    id: '3',
    name: 'Pádraig Ní Fhaoláin',
    handle: '@padraignf',
    county: 'Cork',
    games: 100,
    programmes: 61,
    avatarColor: '#8B2500',
    initials: 'P',
    following: true,
    recentActivity: 'just hit 100 games attended 🎉',
    recentMatch: null,
    timeAgo: '2 days ago',
  },
  {
    id: '4',
    name: 'Fionnuala Casey',
    handle: '@fionnc',
    county: 'Galway',
    games: 21,
    programmes: 19,
    avatarColor: '#1A5C5A',
    initials: 'F',
    following: false,
    recentActivity: null,
    recentMatch: null,
    timeAgo: null,
  },
  {
    id: '5',
    name: 'Niall Ó Murchú',
    handle: '@nialloM',
    county: 'Tipperary',
    games: 67,
    programmes: 44,
    avatarColor: '#1B6B35',
    initials: 'N',
    following: false,
    recentActivity: null,
    recentMatch: null,
    timeAgo: null,
  },
];

export const MILESTONES = [
  { id: '1', icon: '🏟️', name: 'First Game', earned: true },
  { id: '2', icon: '📰', name: 'First Programme', earned: true },
  { id: '3', icon: '🗺️', name: '5 Counties', earned: true },
  { id: '4', icon: '🔥', name: '10 Games', earned: true },
  { id: '5', icon: '💯', name: '50 Games', earned: false },
  { id: '6', icon: '🏆', name: 'All-Ireland', earned: false },
  { id: '7', icon: '📚', name: '25 Programmes', earned: false },
  { id: '8', icon: '🗓️', name: '1 Year', earned: false },
];

export const PROGRAMME_COLOURS = [
  ['#1B6B35', '#28843F'],
  ['#C8952A', '#E8B84B'],
  ['#1C2B6E', '#2E45A8'],
  ['#1A5C5A', '#2E8A87'],
  ['#5C1A5A', '#8A2E87'],
  ['#5C3A1A', '#8A6030'],
];
